/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiFoldersRouteImport } from './routes/api/folders'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiFilesFileIdRouteImport } from './routes/api/files/$fileId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as ApiFilesFileIdDownloadRouteImport } from './routes/api/files/$fileId/download'
import { Route as ApiFilesFileIdPreviewRouteImport } from './routes/api/files/$fileId/preview'
import { Route as ApiFoldersFolderIdFilesRouteImport } from './routes/api/folders/$folderId/files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoldersRoute = ApiFoldersRouteImport.update({
  id: '/api/folders',
  path: '/api/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdRoute = ApiFilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => ApiFilesRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFileIdDownloadRoute = ApiFilesFileIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFilesFileIdPreviewRoute = ApiFilesFileIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiFilesFileIdRoute,
} as any)
const ApiFoldersFolderIdFilesRoute = ApiFoldersFolderIdFilesRouteImport.update({
  id: '/$folderId/files',
  path: '/$folderId/files',
  getParentRoute: () => ApiFoldersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/preview': typeof ApiFilesFileIdPreviewRoute
  '/api/folders/$folderId/files': typeof ApiFoldersFolderIdFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/preview': typeof ApiFilesFileIdPreviewRoute
  '/api/folders/$folderId/files': typeof ApiFoldersFolderIdFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/folders': typeof ApiFoldersRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/files/$fileId': typeof ApiFilesFileIdRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/api/files/$fileId/download': typeof ApiFilesFileIdDownloadRoute
  '/api/files/$fileId/preview': typeof ApiFilesFileIdPreviewRoute
  '/api/folders/$folderId/files': typeof ApiFoldersFolderIdFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/config'
    | '/api/files'
    | '/api/folders'
    | '/api/upload'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/files/$fileId'
    | '/auth/google/callback'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/preview'
    | '/api/folders/$folderId/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/config'
    | '/api/files'
    | '/api/folders'
    | '/api/upload'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/files/$fileId'
    | '/auth/google/callback'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/preview'
    | '/api/folders/$folderId/files'
  id:
    | '__root__'
    | '/'
    | '/api/config'
    | '/api/files'
    | '/api/folders'
    | '/api/upload'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/files/$fileId'
    | '/auth/google/callback'
    | '/api/files/$fileId/download'
    | '/api/files/$fileId/preview'
    | '/api/folders/$folderId/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiFoldersRoute: typeof ApiFoldersRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders': {
      id: '/api/folders'
      path: '/api/folders'
      fullPath: '/api/folders'
      preLoaderRoute: typeof ApiFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId': {
      id: '/api/files/$fileId'
      path: '/$fileId'
      fullPath: '/api/files/$fileId'
      preLoaderRoute: typeof ApiFilesFileIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$fileId/download': {
      id: '/api/files/$fileId/download'
      path: '/download'
      fullPath: '/api/files/$fileId/download'
      preLoaderRoute: typeof ApiFilesFileIdDownloadRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/files/$fileId/preview': {
      id: '/api/files/$fileId/preview'
      path: '/preview'
      fullPath: '/api/files/$fileId/preview'
      preLoaderRoute: typeof ApiFilesFileIdPreviewRouteImport
      parentRoute: typeof ApiFilesFileIdRoute
    }
    '/api/folders/$folderId/files': {
      id: '/api/folders/$folderId/files'
      path: '/$folderId/files'
      fullPath: '/api/folders/$folderId/files'
      preLoaderRoute: typeof ApiFoldersFolderIdFilesRouteImport
      parentRoute: typeof ApiFoldersRoute
    }
  }
}

interface ApiFilesFileIdRouteChildren {
  ApiFilesFileIdDownloadRoute: typeof ApiFilesFileIdDownloadRoute
  ApiFilesFileIdPreviewRoute: typeof ApiFilesFileIdPreviewRoute
}

const ApiFilesFileIdRouteChildren: ApiFilesFileIdRouteChildren = {
  ApiFilesFileIdDownloadRoute: ApiFilesFileIdDownloadRoute,
  ApiFilesFileIdPreviewRoute: ApiFilesFileIdPreviewRoute,
}

const ApiFilesFileIdRouteWithChildren = ApiFilesFileIdRoute._addFileChildren(
  ApiFilesFileIdRouteChildren,
)

interface ApiFilesRouteChildren {
  ApiFilesFileIdRoute: typeof ApiFilesFileIdRouteWithChildren
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesFileIdRoute: ApiFilesFileIdRouteWithChildren,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

interface ApiFoldersRouteChildren {
  ApiFoldersFolderIdFilesRoute: typeof ApiFoldersFolderIdFilesRoute
}

const ApiFoldersRouteChildren: ApiFoldersRouteChildren = {
  ApiFoldersFolderIdFilesRoute: ApiFoldersFolderIdFilesRoute,
}

const ApiFoldersRouteWithChildren = ApiFoldersRoute._addFileChildren(
  ApiFoldersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiFoldersRoute: ApiFoldersRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
